import { expect, test } from '@playwright/test'

test('duration, live finish time and audio choices stay consistent', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-27T19:00:00-07:00') })
  await page.goto('/')
  await expect(page.locator('.finish-preview time')).toHaveText('8:00 PM')
  await page.getByRole('button', { name: '45 min', exact: true }).click()
  await expect(page.locator('.finish-preview time')).toHaveText('7:45 PM')
  await page.clock.fastForward(60_000)
  await expect(page.locator('.finish-preview time')).toHaveText('7:46 PM')
  await page.getByRole('button', { name: 'View session details' }).click()
  await expect(page.getByRole('dialog')).toContainText('Your 45 minutes')
  await expect(page.locator('.details-total')).toContainText('45:00')
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByRole('button', { name: /Audio & gongs/ }).click()
  await page.getByLabel('Opening gong', { exact: true }).selectOption('skip')
  await page.getByLabel('Mettā', { exact: true }).selectOption('play')
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: '45 min', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: /Audio & gongs/ })).toContainText('Mettā on')
  await page.getByRole('button', { name: 'View session details' }).click()
  await expect(page.locator('.details-total')).toContainText('45:00')
  await expect(page.locator('.session-details')).not.toContainText('Gong')
})

test('dismissed drafts do not persist and the reminder traps/restores focus', async ({ page, context }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Audio & gongs/ }).click()
  await page.getByLabel('Mettā', { exact: true }).selectOption('play')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: /Audio & gongs/ })).toBeFocused()
  await expect(page.getByRole('button', { name: /Audio & gongs/ })).toContainText('Mettā off')
  const start = page.getByRole('button', { name: /Start session/ })
  await start.click()
  const dialog = page.getByRole('dialog', { name: 'Keep the app open' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('checkbox')).not.toBeChecked()
  await dialog.getByRole('checkbox').check()
  for (let i = 0; i < 5; i++) {
    await page.keyboard.press('Tab')
    expect(await page.evaluate(() => document.activeElement?.closest('dialog') !== null)).toBe(true)
  }
  await page.keyboard.press('Escape')
  await expect(start).toBeFocused()
  const cookie = (await context.cookies()).find(item => item.name === 'daily_vipassana_preferences')!
  expect(JSON.parse(decodeURIComponent(cookie.value)).hideStartReminder).toBe(false)
  await start.click()
  await expect(dialog.getByRole('checkbox')).not.toBeChecked()
})

test('confirmed reminder preference survives reload and starts the existing audio', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: /Start session/ }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('checkbox').check()
  await dialog.getByRole('button', { name: 'Start session', exact: true }).click()
  await expect(page.getByRole('button', { name: 'End session' })).toBeVisible()
  await expect(page.getByRole('progressbar', { name: 'Recording progress' })).toBeVisible()
  await expect.poll(async () => Number(await page.getByRole('progressbar', { name: 'Recording progress' }).getAttribute('value'))).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Skip recording' }).click()
  await expect(page.getByRole('heading', { name: 'Intro Chanting', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'End session' }).click()
  await page.reload()
  await page.getByRole('button', { name: /Start session/ }).click()
  await expect(page.getByRole('button', { name: 'End session' })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('unchecked confirmation shows the reminder next time', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Start session/ }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Start session', exact: true }).click()
  // Exercise the UI after playback begins; rapid cancellation during audio.load
  // belongs to the existing engine, which this UI change deliberately preserves.
  await expect.poll(async () => Number(await page.getByRole('progressbar', { name: 'Recording progress' }).getAttribute('value'))).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'End session' }).click()
  await page.getByRole('button', { name: /Start session/ }).click()
  await expect(page.getByRole('dialog', { name: 'Keep the app open' })).toBeVisible()
})

test('short custom durations require room for recordings; guided keeps full audio', async ({ page }) => {
  await page.goto('/')
  await page.locator('.duration-presets').getByRole('button', { name: 'Custom', exact: true }).click()
  await page.getByLabel('Minutes', { exact: true }).fill('1')
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Choose at least 12 minutes')
  await expect(page.getByRole('button', { name: /Start session/ })).toBeDisabled()
  await page.getByRole('button', { name: 'Guided', exact: true }).click()
  await expect(page.getByRole('button', { name: /Start session/ })).toContainText('67 min')
  await page.getByLabel('Instructions', { exact: true }).selectOption('long')
  await expect(page.getByRole('button', { name: /Start session/ })).toContainText('66 min')
})

test('theme persists and layouts fit small screens', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.screenshot({ path: testInfo.outputPath('setup-dark.png'), fullPage: true })
  await page.getByRole('button', { name: 'Switch to light theme' }).click()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.screenshot({ path: testInfo.outputPath('setup-light.png'), fullPage: true })
  await page.getByRole('button', { name: /Start session/ }).click()
  await page.screenshot({ path: testInfo.outputPath('reminder-light.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Switch to dark theme' }).click()
  await page.getByRole('button', { name: /Start session/ }).click()
  await page.screenshot({ path: testInfo.outputPath('reminder-dark.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: /Audio & gongs/ }).click()
  await page.screenshot({ path: testInfo.outputPath('audio-sheet.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 320, height: 568 })
  await page.getByRole('button', { name: /Start session/ }).click()
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Start session', exact: true })).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('reminder-small.png'), fullPage: true })
})
