// Generated by npm run audio:metadata. Do not edit measured durations by hand.
export const audioCatalog = {
  "gong": {
    "audioSrc": "/audio/gong.mp3",
    "durationSeconds": 60.033764,
    "sha256": "1a9358d52722bd816ba6929b2c6632d3657636b840227cb2c573bdb3c9cb760d"
  },
  "intro": {
    "audioSrc": "/audio/chanting/default-intro.mp3",
    "durationSeconds": 177.998367,
    "sha256": "baeff570d0c2440345d70fdbfa2c0f30c8e18a966a18ab2ac3121ea82eb71496"
  },
  "instructions": {
    "audioSrc": "/audio/instructions.mp3",
    "durationSeconds": 156.003265,
    "sha256": "a5eae1cda0cd8dfc220961b4384a58ad421908f6b059783f328a5fc4108e14a4"
  },
  "outroChanting": {
    "audioSrc": "/audio/chanting/default-outro.mp3",
    "durationSeconds": 169.000249,
    "sha256": "9762ee9b8d48671f851febfca38265dd3bd35bba61c38afc75e3d977049d69d2"
  },
  "metta": {
    "audioSrc": "/audio/metta.mp3",
    "durationSeconds": 414.014694,
    "sha256": "fb4201c79fb848aa99fc268fed3e482bc03cdcfb0ca5b4ac471e26720cd82b3b"
  },
  "closing": {
    "audioSrc": "/audio/outro.mp3",
    "durationSeconds": 92.835215,
    "sha256": "f194f75487c1a8d90dc381f23b530efb29ce9dcb3d257e854199310070bf9dc5"
  },
  "mettaFadeIn": {
    "audioSrc": "/audio/metta-fade-in.mp3",
    "durationSeconds": 414.002698,
    "sha256": "4ab82e20b5093466500180cb1c1f37544d958f1d090e830c38caabbb2d021a50"
  },
  "closingFadeIn": {
    "audioSrc": "/audio/outro-fade-in.mp3",
    "durationSeconds": 92.850794,
    "sha256": "d2e56e8092fb078a3981f286dbdff500d165925e5a92bef7a58b7886de8f59ec"
  },
  "guidedShort": {
    "audioSrc": "/audio/guided/short.mp3",
    "durationSeconds": 3956.935692,
    "sha256": "60c0c081c945134a7a1506f5f73866105558543b6fc91361f683fd520d3144d0"
  },
  "guidedLong": {
    "audioSrc": "/audio/guided/long.mp3",
    "durationSeconds": 3872.693696,
    "sha256": "6966799e208b816d3c63163b638709e012fef534bc74b63b944774adec9d1aa5"
  }
} as const
